### PR TITLE
ignore newline characters

### PR DESCRIPTION
**Pull request by TetsuyaNegishi**
Added setting to ignore newline characters. 
'\n' and '\r' are not counted if the setting is valid.

### CODE REVIEW

**Comment by nesQuick** [comment]
Hey @TetsuyaNegishi

Thank you very much for this PR. I was not aware that the plugin does count newline characters. I would rather consider this a bug 🐜 then a feature request. This I wanted to ask if you could remove the setting and implement this change right away.

Thanks for your help!

**Comment by TetsuyaNegishi** [comment]
I deleted the setting and changed it to ignore the newline character at all times!

**Comment by nesQuick** [comment]
Thank you very much! Looks good to me. Let get this fella out 🚢

**Comment by nesQuick** [comment]
released with `2.10.4`

**Pull request merged**
