### PR TITLE
#62 Removed space-pen-view dependence

### PR DESCRIPTION
**Pull request by mangecoeur**
replaced atom-space-pen with plain DOM manipulation

### CODE REVIEW

**Comment by nesQuick** [comment]
As you mentioned in #62 that `atom-space-pen` is deprecated I wonder where you got the information? Because the github repo does not say anything about this and neither the atom docs do. I also think that using the view abstraction atom provides is a better solution then just doing it on the raw DOM.

**Comment by mangecoeur** [comment]
From the readme at https://github.com/atom-archive/space-pen :

> :rotating_light: This library is no longer maintained :rotating_light:

The confusion might come because 'atom-space-pen-views' was used in stead of 'space-pen', even though none of the special Atom views (TextEditor, ScrollPane, ...) were being used. Modern DOM is a good approach, and the one the Atom devs took internally after trying different abstractions. Plus pulling in a view library to create 4 divs is overkill IMHO .

**Comment by nesQuick** [comment]
Sorry for the delay, I tried to merge and test it just now and found the following error:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [wordcount](https://github.com/nesQuick/atom-wordcount) package, v2.6.2


### Stack Trace

Uncaught TypeError: this.height is not a function

```
At /Users/ole/projects/atom-wordcount/lib/wordcount-view.coffee:30

TypeError: this.height is not a function
    at WordcountView.module.exports.WordcountView.update_count (/Users/ole/projects/atom-wordcount/lib/wordcount-view.coffee:30:17)
    at /Users/ole/projects/atom-wordcount/lib/main.coffee:62:14
    at debounced (/Users/ole/projects/atom-wordcount/node_modules/lodash/index.js:7737:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.selectionRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2310:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:930:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:264:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:65:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:396:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:342:12)
    at Marker.module.exports.Marker.clearTail (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:187:19)
    at TextEditorMarker.module.exports.TextEditorMarker.clearTail (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:215:32)
    at Selection.module.exports.Selection.clear (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:193:21)
    at Cursor.module.exports.Cursor.clearSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:624:55)
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:670:12)
    at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:65:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1560:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1780:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1559:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:757:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
     -0:50.8.0 window:toggle-dev-tools (atom-text-editor.editor.mini.is-focused)
     -0:15.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  6x -0:14.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:12.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "policeman-rubocop",
      "policeman",
      "cucumber-runner",
      "feedback",
      "vim-mode",
      "test-status",
      "language-rspec"
    ]
  },
  "wordcount": {
    "goal": 50,
    "ignorecode": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jasmine, v0.8.1
auto-update-packages, v1.0.1
autocomplete-go, v1.1.0
builder-go, v1.0.0
coffee-compile, v0.21.1
command-logger, v0.23.0
css-color-underline, v1.0.1
cucumber, v0.5.0
editor-stats, v0.17.0
environment, v1.2.0
file-icons, v1.7.17
git-log, v0.4.1
go-config, v1.2.1
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
language-docker, v1.1.6
language-elixir, v0.15.0
language-haml, v0.24.0
language-jade, v0.7.1
language-javascript-jsx, v0.3.7
language-julia, v2.0.0
language-rust, v0.4.6
language-slim, v0.5.0
language-terraform, v0.7.4
linter, v1.11.14
linter-js-standard, v3.4.1
linter-write-good, v0.7.0
minimap, v4.24.7
minimap-find-and-replace, v4.5.1
minimap-selection, v4.4.0
navigator-godef, v1.0.3
pretty-json, v1.4.4
regex-railroad-diagram, v0.16.0
tester-go, v1.0.4
travis-ci-status, v1.1.1
visual-bell, v1.0.0
wordcount, v2.6.2

# Dev
No dev packages
```

@mangecoeur would you mind to check this and also rebase so I could get this in :)

**Comment by mangecoeur** [comment]
Hi, sorry I only just now saw your comment :/ I updated the PR accordingly, should now be on master, hopefully rebased correctly, seems to be conflit free now :)

**Comment by nesQuick** [comment]
@mangecoeur thanks a lot for this, especially maintenance work does  to get that many love. Thank you ✨

**Pull request merged**
