### PR TITLE
Only update counts if view is visible

### LINKED ISSUE #73: Words are counted even when the result is not viewed
A thing I came across trying to implement #72.

### PR DESCRIPTION
**Pull request by villermen**
Fixes #73.

### CODE REVIEW

**Comment by nesQuick** [comment]
Thank you very much for the contribution! As you are tracking state in a global variable I wonder if this still works as expected with a split pane. Or if that should rather be bound to the view?

**Comment by villermen** [comment]
Split panes should not be a problem, as there is only one status bar and the count gets updated when the active pane changes.

I just tested this and there does seem to be a small issue with the first cursor reposition in another pane. Sometimes (and only sometimes) it will not update the count when positioning before a line break in another pane. I have no idea what causes this however.

**Comment by villermen** [comment]
This is not due to the visible variable though, as the visibility and the variable consistently switch when changing active items between panes where one should and one shouldn't show counts.

**Comment by villermen** [comment]
Oh I got it: It's not when positioned before a line break, but it's when changing item without changing selection (I clicked the same spot only when I positioned the cursor before a line break). Fixing now...

**Comment by villermen** [comment]
I'm trying to update the view and count together wherever only the view was updated before. I'm stuck trying to get a valid editor to update_count. I moved update_count outside of the observable, but for some reason an object is still passed to view.update_count

```coffeescript
  activate: (state) ->
    view = new WordcountView()

    update_count = _.throttle (editor) ->
      visible && view.update_count(editor)
    , 300

    atom.workspace.observeTextEditors (editor) ->
      editor.onDidChange update_count
      editor.onDidChangeSelectionRange update_count

    update_view_and_count = (item) =>
      @show_or_hide_for_item item
      update_count atom.workspace.getActiveTextEditor()

    atom.workspace.onDidChangeActivePaneItem update_view_and_count

    update_view_and_count atom.workspace.getActivePaneItem()

    atom.config.observe('wordcount.goal', @update_goal)
```

This is the part where I admit this is the first time I code in CoffeeScript, and that I can't figure this one out. =S

**Comment by villermen** [comment]
I did figure it out. It updates immediately on pane switch now.

**Comment by nesQuick** [comment]
I will test the PR's today :)

**Comment by nesQuick** [comment]
Just checked it, works fine, also with splitpane 👍

**Comment by nesQuick** [comment]
Thank you very much for this addition as well ✨

**Comment by villermen** [comment]
Most welcome.

**Pull request merged**
