### PR TITLE
Update wordcount.cson

### PR DESCRIPTION
**Pull request by claman**
This should fix https://github.com/nesQuick/atom-wordcount/issues/17
I'll keep mucking around to see if I can fix https://github.com/nesQuick/atom-wordcount/issues/19

### CODE REVIEW

**Comment by nesQuick** [comment]
thanks for your help with fixing this :+1: :tada:

**Comment by claman** [comment]
You're welcome!

In terms of trying to fix the issue with `atom.workspaceView.getActivePaneItem()`, I tried changing all calls to `atom.workspaceView` in `lib/wordcount-view.coffee` to `atom.workspace`, which seems like it worked (I don't know anywhere near enough to feel confident saying that), but then I ran into https://github.com/nesQuick/atom-wordcount/issues/16

**Comment by nesQuick** [comment]
@claman hmm, thanks for putting the effort into this: it's been a while until I looked into who to develop these plugins myself. That's why I have out of nothing no idea what might cause this.

**Comment by claman** [comment]
@nesQuick you're quite welcome. No problem at all. I'm having fun trying to figure some of these things out myself.

**Comment by nesQuick** [comment]
@claman awesome. I will publish a new release asap so we can have a few fixes out already! :)

**Comment by claman** [comment]
Sweet. I've made a few other changes to `lib/wordcount-view.coffee`. Should I just make another pull request?

**Comment by nesQuick** [comment]
Yes please! So we can discuss things there, if there is anything to
discuss. Please always pull request :)

**Pull request merged**
